export const specializationFields = {

  // ─── HOMEOPATHY ───────────────────────────────────────────────────────────
  'Classical Homeopathy': [
    ['constitutionalType', 'Constitutional Type'],
    ['miasm', 'Miasm'],
    ['mentalSymptoms', 'Mental / Emotional Symptoms'],
    ['physicalGenerals', 'Physical Generals'],
    ['particulars', 'Particulars'],
    ['modalities', 'Modalities (Better / Worse)'],
    ['sensations', 'Sensations'],
    ['thermalReaction', 'Thermal Reaction'],
    ['desireAversion', 'Desires & Aversions'],
    ['previousRemedies', 'Previous Homeopathic Remedies'],
  ],

  'Clinical Homeopathy': [
    ['condition', 'Condition / Diagnosis'],
    ['acuteOrChronic', 'Acute / Chronic'],
    ['mainSymptoms', 'Main Symptoms'],
    ['associatedComplaints', 'Associated Complaints'],
    ['onset', 'Onset & Duration'],
    ['aggravatingFactors', 'Aggravating Factors'],
    ['relievingFactors', 'Relieving Factors'],
    ['previousTreatment', 'Previous Treatment'],
  ],

  'Pediatric Homeopathy': [
    ['childAge', 'Child Age'],
    ['birthHistory', 'Birth / Perinatal History'],
    ['developmentalMilestones', 'Developmental Milestones'],
    ['mainComplaint', 'Main Complaint'],
    ['feeding', 'Feeding (Breast / Formula / Solids)'],
    ['temperament', 'Child Temperament'],
    ['vaccineHistory', 'Vaccination History'],
    ['previousRemedies', 'Previous Remedies'],
  ],

  "Women's Homeopathy": [
    ['menstrualCycle', 'Menstrual Cycle'],
    ['lastMenstrualPeriod', 'Last Menstrual Period'],
    ['menstrualComplaints', 'Menstrual Complaints'],
    ['obstetricHistory', 'Obstetric History'],
    ['hormonalIssues', 'Hormonal Issues'],
    ['contraceptiveUse', 'Contraceptive Use'],
    ['menopausalStatus', 'Menopausal Status'],
    ['previousRemedies', 'Previous Remedies'],
  ],

  'Chronic Disease Homeopathy': [
    ['diagnosis', 'Diagnosed Condition'],
    ['duration', 'Duration of Illness'],
    ['currentAllopathicMeds', 'Current Allopathic Medications'],
    ['progressionHistory', 'Disease Progression History'],
    ['systemsInvolved', 'Systems Involved'],
    ['qualityOfLife', 'Impact on Quality of Life'],
    ['previousRemedies', 'Previous Homeopathic Remedies'],
    ['labReports', 'Recent Lab Reports / Investigations'],
  ],

  'Mental Health Homeopathy': [
    ['mentalDiagnosis', 'Mental Health Diagnosis'],
    ['chiefMentalComplaint', 'Chief Mental Complaint'],
    ['triggersStressors', 'Triggers / Stressors'],
    ['sleepPattern', 'Sleep Pattern'],
    ['anxietyLevel', 'Anxiety Level (1–10)'],
    ['moodPattern', 'Mood Pattern'],
    ['currentPsychMeds', 'Current Psychiatric Medications'],
    ['previousRemedies', 'Previous Homeopathic Remedies'],
  ],

  'Geriatric Homeopathy': [
    ['ageRelatedComplaints', 'Age-Related Complaints'],
    ['comorbidities', 'Comorbidities'],
    ['currentMedications', 'Current Medications'],
    ['mobilityStatus', 'Mobility Status'],
    ['cognitiveStatus', 'Cognitive Status'],
    ['fallHistory', 'History of Falls'],
    ['nutritionalStatus', 'Nutritional Status'],
    ['previousRemedies', 'Previous Homeopathic Remedies'],
  ],

  'Skin & Hair Homeopathy': [
    ['skinCondition', 'Skin Condition'],
    ['locationOfLesions', 'Location of Lesions'],
    ['appearance', 'Appearance (Rash / Eruption Type)'],
    ['itching', 'Itching'],
    ['dischargeType', 'Discharge Type'],
    ['hairLossPattern', 'Hair Loss Pattern'],
    ['scalp', 'Scalp Condition'],
    ['triggers', 'Triggers (Food / Season / Stress)'],
    ['previousTreatment', 'Previous Treatment'],
  ],

  'Allergy Homeopathy': [
    ['allergenType', 'Known Allergen'],
    ['allergySymptoms', 'Allergy Symptoms'],
    ['seasonality', 'Seasonal / Perennial'],
    ['eyeInvolvement', 'Eye Involvement'],
    ['nasalSymptoms', 'Nasal Symptoms'],
    ['skinReactions', 'Skin Reactions'],
    ['asthmaLink', 'Associated Asthma'],
    ['previousAntiAllergy', 'Previous Anti-Allergy Treatment'],
  ],

  'Acute Care Homeopathy': [
    ['acuteCondition', 'Acute Condition'],
    ['onset', 'Sudden / Gradual Onset'],
    ['fever', 'Fever'],
    ['mainSymptom', 'Main Symptom'],
    ['associatedSymptoms', 'Associated Symptoms'],
    ['modalities', 'Modalities'],
    ['recentExposure', 'Recent Exposure / Travel / Infection'],
    ['firstAidGiven', 'First Aid / Medication Given'],
  ],

  // ─── GENERAL MEDICINE ─────────────────────────────────────────────────────
  'Internal Medicine': [
    ['bloodPressure', 'Blood Pressure'],
    ['temperature', 'Temperature'],
    ['pulse', 'Pulse'],
    ['weight', 'Weight'],
    ['bmi', 'BMI'],
    ['spo2', 'SpO₂'],
    ['chiefComplaintSystem', 'System Involved'],
    ['investigations', 'Recent Investigations'],
  ],

  Diabetology: [
    ['diabetesType', 'Diabetes Type'],
    ['diagnosedYear', 'Year of Diagnosis'],
    ['fastingBloodSugar', 'Fasting Blood Sugar'],
    ['postPrandialSugar', 'Post-Prandial Sugar'],
    ['hba1c', 'HbA1c (%)'],
    ['insulinUse', 'Insulin Use'],
    ['oralMeds', 'Oral Hypoglycemic Agents'],
    ['complications', 'Diabetic Complications'],
    ['dietControl', 'Diet Control'],
    ['selfMonitoring', 'Self-Monitoring of Blood Glucose'],
  ],

  'Hypertension Clinic': [
    ['bp', 'Blood Pressure (mmHg)'],
    ['heartRate', 'Heart Rate'],
    ['bpDuration', 'Duration of Hypertension'],
    ['antihypertensives', 'Current Antihypertensives'],
    ['organDamage', 'End-Organ Damage'],
    ['kidneyFunction', 'Kidney Function (eGFR / Creatinine)'],
    ['ecgFindings', 'ECG Findings'],
    ['saltIntake', 'Salt Intake'],
    ['adherence', 'Medication Adherence'],
  ],

  'Fever & Infection Clinic': [
    ['feverDays', 'Duration of Fever (Days)'],
    ['peakTemperature', 'Peak Temperature'],
    ['feverPattern', 'Fever Pattern (Continuous / Intermittent)'],
    ['chills', 'Chills / Rigors'],
    ['travelHistory', 'Travel History'],
    ['exposureHistory', 'Exposure History'],
    ['wbc', 'WBC Count'],
    ['malariaTestResult', 'Malaria / Dengue / Typhoid Test'],
    ['antibioticsGiven', 'Antibiotics Given'],
  ],

  'Thyroid Clinic': [
    ['thyroidCondition', 'Thyroid Condition'],
    ['tsh', 'TSH Level'],
    ['ft3ft4', 'Free T3 / T4'],
    ['thyroidAntibodies', 'Thyroid Antibodies (TPO / TG)'],
    ['thyroidUltrasound', 'Thyroid Ultrasound Findings'],
    ['currentThyroidMeds', 'Current Thyroid Medication & Dose'],
    ['symptoms', 'Current Symptoms'],
    ['nodules', 'Nodule Present'],
  ],

  'Lifestyle Disease Clinic': [
    ['bmi', 'BMI'],
    ['waistCircumference', 'Waist Circumference (cm)'],
    ['metabolicSyndrome', 'Metabolic Syndrome Features'],
    ['physicalActivity', 'Physical Activity Level'],
    ['dietType', 'Diet Type'],
    ['lipidProfile', 'Lipid Profile'],
    ['liverFunction', 'Liver Function (NAFLD)'],
    ['sleepQuality', 'Sleep Quality'],
    ['stressLevel', 'Stress Level'],
  ],

  'Travel Medicine': [
    ['destination', 'Travel Destination'],
    ['travelDate', 'Travel Date'],
    ['travelDuration', 'Duration of Travel'],
    ['purposeOfTravel', 'Purpose of Travel'],
    ['vaccinesGiven', 'Vaccines Administered'],
    ['malariaRegion', 'Malaria-Endemic Region'],
    ['prophylaxis', 'Malaria Prophylaxis'],
    ['currentHealth', 'Current Health Status'],
    ['travelInsurance', 'Travel Insurance'],
  ],

  'Occupational Health': [
    ['occupation', 'Occupation'],
    ['employer', 'Employer / Workplace'],
    ['exposureType', 'Occupational Exposure (Chemical / Physical / Biological)'],
    ['durationOfExposure', 'Duration of Exposure'],
    ['ppe', 'PPE Used'],
    ['workRelatedSymptoms', 'Work-Related Symptoms'],
    ['incidentReport', 'Incident / Accident Report'],
    ['fitForWork', 'Fit for Work Assessment'],
  ],

  'Geriatric Medicine': [
    ['age', 'Age'],
    ['comorbidities', 'Comorbidities'],
    ['polypharmacy', 'Number of Medications'],
    ['fallRisk', 'Fall Risk Assessment'],
    ['cognition', 'Cognitive Screen (MMSE)'],
    ['adl', 'Activities of Daily Living (ADL)'],
    ['nutritionRisk', 'Nutrition Risk'],
    ['socialSupport', 'Social Support'],
    ['mobility', 'Mobility Aid Used'],
  ],

  'Preventive Medicine': [
    ['screeningAge', 'Age for Screening'],
    ['cancerScreening', 'Cancer Screening Done'],
    ['vaccineHistory', 'Vaccination History'],
    ['lipidScreening', 'Lipid Screening'],
    ['colonoscopyDue', 'Colonoscopy Due'],
    ['mammogram', 'Mammogram / PSA'],
    ['boneDesnsity', 'Bone Density (DEXA)'],
    ['lifestyleRisk', 'Lifestyle Risk Factors'],
  ],

  // ─── CARDIOLOGY ───────────────────────────────────────────────────────────
  'Interventional Cardiology': [
    ['chestPain', 'Chest Pain (Type / Duration)'],
    ['angiographyReport', 'Angiography Findings'],
    ['ejectionFraction', 'Ejection Fraction (%)'],
    ['lesionVessel', 'Vessel / Lesion Location'],
    ['stentType', 'Stent Type'],
    ['antiplateletTherapy', 'Antiplatelet Therapy'],
    ['previousPCI', 'Previous PCI / CABG'],
    ['ecgChanges', 'ECG Changes'],
    ['troponinLevel', 'Troponin Level'],
  ],

  Electrophysiology: [
    ['arrhythmiaType', 'Arrhythmia Type'],
    ['palpitationFrequency', 'Palpitation Frequency'],
    ['syncope', 'Syncope / Pre-syncope'],
    ['holterFindings', 'Holter Monitor Findings'],
    ['ablationDone', 'Previous Ablation'],
    ['pacemakerICD', 'Pacemaker / ICD Present'],
    ['antiarrhythmicDrugs', 'Current Antiarrhythmic Drugs'],
    ['ecgFindings', 'Resting ECG Findings'],
  ],

  Echocardiography: [
    ['indication', 'Indication for Echo'],
    ['ef', 'Ejection Fraction (%)'],
    ['wallMotion', 'Wall Motion Abnormality'],
    ['valveDisease', 'Valve Disease'],
    ['pericardialEffusion', 'Pericardial Effusion'],
    ['lvhypertrophy', 'LV Hypertrophy'],
    ['rvFunction', 'RV Function'],
    ['previousEcho', 'Previous Echo Date & Findings'],
  ],

  'Heart Failure Clinic': [
    ['nyhaClass', 'NYHA Functional Class'],
    ['ejectionFraction', 'Ejection Fraction (%)'],
    ['bnp', 'BNP / NT-proBNP Level'],
    ['fluidRetention', 'Fluid Retention / Oedema'],
    ['diuretics', 'Diuretic Therapy'],
    ['deviceTherapy', 'Device Therapy (CRT / ICD)'],
    ['hospitalisations', 'HF Hospitalisations (Last 12 Months)'],
    ['weightMonitoring', 'Daily Weight Monitoring'],
    ['dietarySodium', 'Dietary Sodium Restriction'],
  ],

  'Preventive Cardiology': [
    ['framinghamScore', 'Framingham Risk Score'],
    ['ldlTarget', 'LDL Target (mmol/L)'],
    ['statinTherapy', 'Statin Therapy'],
    ['aspirinUse', 'Aspirin Use'],
    ['bpControl', 'Blood Pressure Control'],
    ['smokingStatus', 'Smoking Status'],
    ['diabetesControl', 'Diabetes Control (HbA1c)'],
    ['dietExercise', 'Diet & Exercise Counselling'],
  ],

  'Pediatric Cardiology': [
    ['congenitalDefect', 'Congenital Heart Defect'],
    ['cyanosis', 'Cyanosis Present'],
    ['echoFindings', 'Echo Findings'],
    ['growthConcern', 'Growth / Feeding Concern'],
    ['surgeryHistory', 'Previous Cardiac Surgery'],
    ['catheterizationDone', 'Cardiac Catheterization Done'],
    ['currentMeds', 'Current Cardiac Medications'],
  ],

  'Cardiac Rehabilitation': [
    ['cardiacEvent', 'Cardiac Event (MI / CABG / PCI)'],
    ['eventDate', 'Event Date'],
    ['currentExerciseTolerance', 'Exercise Tolerance (METs)'],
    ['rehabPhase', 'Rehabilitation Phase'],
    ['exercisePrescription', 'Exercise Prescription'],
    ['dietCounselling', 'Diet Counselling'],
    ['psychosocialSupport', 'Psychosocial Support Needed'],
    ['smokingCessation', 'Smoking Cessation'],
  ],

  'Vascular Cardiology': [
    ['vasculatureInvolved', 'Vasculature Involved'],
    ['ankleIndex', 'Ankle-Brachial Index (ABI)'],
    ['claudicationDistance', 'Claudication Distance (m)'],
    ['duplexFindings', 'Duplex Ultrasound Findings'],
    ['angiographyReport', 'Angiography Report'],
    ['anticoagulation', 'Anticoagulation Therapy'],
    ['woundVascularStatus', 'Wound / Vascular Status'],
  ],

  'Nuclear Cardiology': [
    ['testType', 'Test Type (SPECT / PET)'],
    ['stressProtocol', 'Stress Protocol'],
    ['ischemiaPattern', 'Ischemia Pattern'],
    ['perfusionDefect', 'Perfusion Defect'],
    ['ef', 'Gated LVEF (%)'],
    ['clinicalQuestion', 'Clinical Question'],
    ['previousTest', 'Previous Nuclear Study'],
  ],

  'Hypertensive Heart Disease': [
    ['bp', 'Blood Pressure (mmHg)'],
    ['lvhPresent', 'LVH on ECG / Echo'],
    ['diastolicDysfunction', 'Diastolic Dysfunction Grade'],
    ['kidneyFunction', 'Kidney Function'],
    ['retinalChanges', 'Retinal Changes'],
    ['antihypertensives', 'Current Antihypertensives'],
    ['compliance', 'Medication Compliance'],
  ],

  // ─── NEUROLOGY ────────────────────────────────────────────────────────────
  'Stroke & Cerebrovascular': [
    ['strokeType', 'Stroke Type (Ischaemic / Haemorrhagic)'],
    ['strokeOnset', 'Time of Onset'],
    ['nihssScore', 'NIHSS Score'],
    ['mriCtFindings', 'MRI / CT Findings'],
    ['thrombolysisGiven', 'Thrombolysis / Thrombectomy'],
    ['deficits', 'Neurological Deficits'],
    ['riskFactors', 'Vascular Risk Factors'],
    ['antiplateletAnticoag', 'Antiplatelet / Anticoagulant'],
  ],

  'Epilepsy Clinic': [
    ['seizureType', 'Seizure Type'],
    ['seizureFrequency', 'Seizure Frequency'],
    ['lastSeizure', 'Date of Last Seizure'],
    ['eegFindings', 'EEG Findings'],
    ['mriFindings', 'MRI Brain Findings'],
    ['aedCurrent', 'Current AEDs & Doses'],
    ['triggers', 'Seizure Triggers'],
    ['seizureDiary', 'Seizure Diary Kept'],
    ['drivingStatus', 'Driving Status'],
  ],

  'Movement Disorders': [
    ['condition', 'Condition (Parkinson / Tremor / Dystonia)'],
    ['onsetAge', 'Age of Onset'],
    ['motorSymptoms', 'Motor Symptoms'],
    ['nonMotorSymptoms', 'Non-Motor Symptoms'],
    ['updrsScore', 'UPDRS Score'],
    ['dopaminergicMeds', 'Dopaminergic Medications'],
    ['dbs', 'DBS / Device Therapy'],
    ['fallsHistory', 'Falls History'],
  ],

  'Headache & Migraine': [
    ['headacheType', 'Headache Type'],
    ['frequency', 'Headache Frequency (days/month)'],
    ['severity', 'Severity (VAS 1–10)'],
    ['location', 'Location / Side'],
    ['aura', 'Aura Present'],
    ['nausea', 'Nausea / Vomiting'],
    ['photophobia', 'Photophobia / Phonophobia'],
    ['acuteMeds', 'Acute Medications'],
    ['prophylaxis', 'Prophylactic Medications'],
    ['triggerFactors', 'Trigger Factors'],
  ],

  'Neuromuscular Disease': [
    ['condition', 'Condition (MD / MG / Neuropathy)'],
    ['distribution', 'Muscle Weakness Distribution'],
    ['emgNcsFindings', 'EMG / NCS Findings'],
    ['antibodies', 'Relevant Antibodies (AChR / MuSK)'],
    ['muscleEnzymes', 'Muscle Enzymes (CK)'],
    ['respiratoryFunction', 'Respiratory Function (FVC)'],
    ['swallowing', 'Swallowing Difficulty'],
    ['currentMeds', 'Current Medications'],
  ],

  'Multiple Sclerosis Clinic': [
    ['msType', 'MS Type (RRMS / SPMS / PPMS)'],
    ['diagnosedYear', 'Year of Diagnosis'],
    ['edssScore', 'EDSS Score'],
    ['relapsesLastYear', 'Relapses (Last 12 Months)'],
    ['dmt', 'Disease-Modifying Therapy'],
    ['mriActivity', 'MRI Activity (New Lesions)'],
    ['bladderBowel', 'Bladder / Bowel Symptoms'],
    ['fatigue', 'Fatigue Level (1–10)'],
  ],

  'Cognitive Neurology': [
    ['cognitiveComplaint', 'Chief Cognitive Complaint'],
    ['mmseScore', 'MMSE / MoCA Score'],
    ['dementiaSyndrome', 'Dementia Syndrome (AD / VaD / LBD)'],
    ['onsetPattern', 'Onset Pattern (Gradual / Stepwise)'],
    ['adlImpact', 'ADL Impairment'],
    ['behavioural', 'Behavioural Symptoms'],
    ['medications', 'Current Medications (Cholinesterase Inhibitors)'],
    ['carerStress', 'Carer Stress Level'],
  ],

  'Neuro-Ophthalmology': [
    ['visualSymptom', 'Visual Symptom'],
    ['visionLossPattern', 'Pattern (Monocular / Binocular)'],
    ['onset', 'Onset (Sudden / Gradual)'],
    ['fundusFindings', 'Fundus Findings'],
    ['mriFindings', 'MRI Brain / Orbits Findings'],
    ['visualFieldResult', 'Visual Field Test Result'],
    ['pupilAbnormality', 'Pupil Abnormality'],
    ['doublevision', 'Double Vision (Diplopia)'],
  ],

  'Sleep Disorders': [
    ['sleepComplaint', 'Sleep Complaint (Insomnia / Apnea / RLS)'],
    ['sleepDuration', 'Average Sleep Duration (hrs)'],
    ['ess', 'Epworth Sleepiness Scale Score'],
    ['polysomnography', 'Polysomnography / HST Result'],
    ['ahiIndex', 'AHI Index'],
    ['cpapUse', 'CPAP / BiPAP Use'],
    ['circadianIssue', 'Circadian Rhythm Disorder'],
    ['currentMeds', 'Current Sleep Medications'],
  ],

  'Pediatric Neurology': [
    ['childAge', 'Age of Child'],
    ['developmentalDelay', 'Developmental Delay'],
    ['milestonesMissed', 'Milestones Missed'],
    ['seizuresPresent', 'Seizures Present'],
    ['eegResult', 'EEG Result'],
    ['mriFindings', 'MRI Brain Findings'],
    ['neurodevelopmentalDx', 'Neurodevelopmental Diagnosis'],
    ['therapyOngoing', 'Therapy (PT / OT / Speech)'],
  ],

  // ─── ORTHOPEDICS ──────────────────────────────────────────────────────────
  'Bone Specialist': [
    ['boneCondition', 'Bone Condition'],
    ['fractureHistory', 'Fracture History'],
    ['boneDesnsity', 'DEXA Scan Result (T-score)'],
    ['calcium', 'Calcium Level'],
    ['vitaminD', 'Vitamin D Level'],
    ['bisphosphonate', 'Bisphosphonate Therapy'],
    ['painScore', 'Pain Score (VAS 1–10)'],
    ['xrayFindings', 'X-Ray Findings'],
  ],

  'Joint Replacement': [
    ['jointInvolved', 'Joint Involved (Hip / Knee / Shoulder)'],
    ['oaGrade', 'OA Grade (KL Grade)'],
    ['painScore', 'Pain Score (VAS 1–10)'],
    ['walkingDistance', 'Walking Distance (m)'],
    ['implantType', 'Implant Type'],
    ['previousSurgery', 'Previous Joint Surgery'],
    ['bmi', 'BMI'],
    ['anaesthesiaFitness', 'Anaesthesia Fitness'],
  ],

  'Spine Surgery': [
    ['spineLevel', 'Spine Level Affected'],
    ['diagnosis', 'Diagnosis (PIVD / Stenosis / Scoliosis)'],
    ['radiculopathy', 'Radiculopathy Present'],
    ['mriFindings', 'MRI Spine Findings'],
    ['motorDeficit', 'Motor Deficit'],
    ['sensoryDeficit', 'Sensory Deficit'],
    ['bladderBowel', 'Bladder / Bowel Involvement'],
    ['vaspScore', 'VAS Pain Score'],
    ['physiotherapy', 'Physiotherapy Trial'],
  ],

  'Sports Medicine': [
    ['sport', 'Sport / Activity'],
    ['injuryType', 'Injury Type'],
    ['injuryMechanism', 'Mechanism of Injury'],
    ['affectedStructure', 'Affected Structure (Ligament / Tendon / Muscle)'],
    ['mriUltrasound', 'MRI / Ultrasound Findings'],
    ['functionalImpairment', 'Functional Impairment'],
    ['returnToSportGoal', 'Return to Sport Goal'],
    ['rehabStage', 'Rehabilitation Stage'],
  ],

  'Pediatric Orthopedics': [
    ['childAge', 'Age of Child'],
    ['deformity', 'Deformity / Condition'],
    ['side', 'Side Affected'],
    ['xrayFindings', 'X-Ray Findings'],
    ['functionalImpact', 'Functional Impact'],
    ['brace', 'Brace / Orthosis Used'],
    ['surgeryPlanned', 'Surgery Planned'],
    ['growthPlate', 'Growth Plate Concern'],
  ],

  'Hand & Upper Limb': [
    ['upperLimbCondition', 'Condition'],
    ['side', 'Side (Right / Left)'],
    ['functionLoss', 'Function Loss'],
    ['nerveDamage', 'Nerve Involvement'],
    ['tendonStatus', 'Tendon Status'],
    ['xrayFindings', 'X-Ray / MRI Findings'],
    ['cts', 'Carpal Tunnel / NCS'],
    ['occupation', 'Occupation / Dominant Hand'],
  ],

  'Foot & Ankle': [
    ['footCondition', 'Condition (Bunion / Flat Foot / Deformity)'],
    ['side', 'Side Affected'],
    ['weightBearing', 'Weight Bearing Status'],
    ['xrayFindings', 'X-Ray Findings'],
    ['orthosis', 'Orthosis / Insole Used'],
    ['previousInjection', 'Previous Steroid Injection'],
    ['diabeticFoot', 'Diabetic Foot Assessment'],
    ['footwear', 'Current Footwear'],
  ],

  'Trauma Surgery': [
    ['traumaMechanism', 'Mechanism of Trauma'],
    ['fractureType', 'Fracture Type / Location'],
    ['openClosed', 'Open / Closed Fracture'],
    ['atatusGCS', 'GCS / ATLS Status'],
    ['imagingFindings', 'X-Ray / CT Findings'],
    ['neurovascularStatus', 'Neurovascular Integrity'],
    ['fixationMethod', 'Fixation Method (ORIF / IM Nail / Ex-Fix)'],
    ['tetanusStatus', 'Tetanus Status'],
  ],

  Arthroscopy: [
    ['joint', 'Joint (Knee / Shoulder / Hip)'],
    ['indication', 'Indication for Arthroscopy'],
    ['mriFindings', 'MRI Findings'],
    ['tearsPresent', 'Tears (Meniscus / Labrum / Rotator Cuff)'],
    ['instability', 'Instability Present'],
    ['cartilageStatus', 'Cartilage Status'],
    ['procedurePlanned', 'Procedure Planned'],
    ['previousSurgery', 'Previous Arthroscopy / Surgery'],
  ],

  'Rheumatology-Ortho': [
    ['inflammatoryDx', 'Inflammatory Diagnosis'],
    ['jointsInvolved', 'Joints Involved'],
    ['swelling', 'Joint Swelling'],
    ['morningStiffness', 'Morning Stiffness (Duration)'],
    ['crpEsr', 'CRP / ESR'],
    ['rfAntiCcp', 'RF / Anti-CCP'],
    ['dmards', 'DMARD / Biologic Therapy'],
    ['xrayErosions', 'X-Ray Erosions / Joint Damage'],
  ],

  // ─── PEDIATRICS ───────────────────────────────────────────────────────────
  Neonatology: [
    ['gestationalAge', 'Gestational Age (weeks)'],
    ['birthWeight', 'Birth Weight (g)'],
    ['apgarScore', 'APGAR Score (1 min / 5 min)'],
    ['deliveryMode', 'Mode of Delivery'],
    ['neonatalComplication', 'Neonatal Complication'],
    ['nicu', 'NICU Admission'],
    ['feeding', 'Feeding Method'],
    ['screeningTests', 'Newborn Screening Tests'],
  ],

  'Pediatric Gastroenterology': [
    ['ageOfChild', 'Age of Child'],
    ['giComplaint', 'GI Complaint'],
    ['growthPattern', 'Growth Pattern (Height / Weight)'],
    ['stoolPattern', 'Stool Pattern / Appearance'],
    ['vomiting', 'Vomiting'],
    ['abdominalPain', 'Abdominal Pain'],
    ['celiacTest', 'Celiac / Allergy Test'],
    ['colonoscopyBiopsy', 'Endoscopy / Biopsy Done'],
  ],

  'Pediatric Pulmonology': [
    ['ageOfChild', 'Age of Child'],
    ['pulmonaryCondition', 'Condition (Asthma / CF / Wheeze)'],
    ['coughPattern', 'Cough Pattern'],
    ['wheeze', 'Wheeze Present'],
    ['spirometry', 'Spirometry Results'],
    ['cftr', 'CF Genotype / Sweat Test'],
    ['inhaler', 'Inhaler Technique & Compliance'],
    ['hospitalisations', 'Hospitalisations (Last 12 Months)'],
  ],

  'Pediatric Endocrinology': [
    ['ageOfChild', 'Age of Child'],
    ['endoCondition', 'Condition (Growth / DM / Thyroid)'],
    ['heightSD', 'Height SDS'],
    ['weightSD', 'Weight SDS'],
    ['boneAge', 'Bone Age (X-Ray)'],
    ['ghDeficiency', 'GH Deficiency / Stimulation Test'],
    ['pubertyStage', 'Pubertal Stage (Tanner)'],
    ['hormoneLevels', 'Hormone Levels'],
  ],

  'Developmental Pediatrics': [
    ['ageOfChild', 'Age of Child'],
    ['developmentalConcern', 'Developmental Concern'],
    ['autismScreening', 'Autism Screening (M-CHAT / ADOS)'],
    ['adhdScreening', 'ADHD Screening (Vanderbilt)'],
    ['speechDelay', 'Speech / Language Delay'],
    ['motorDelay', 'Gross / Fine Motor Delay'],
    ['schoolPerformance', 'School Performance'],
    ['therapiesOngoing', 'Therapies (ABA / Speech / OT)'],
    ['medications', 'Current Medications'],
  ],

  'Pediatric Oncology': [
    ['cancerType', 'Cancer Type / Diagnosis'],
    ['ageAtDiagnosis', 'Age at Diagnosis'],
    ['stage', 'Disease Stage'],
    ['chemoCycle', 'Current Chemo Cycle & Protocol'],
    ['bloodCounts', 'CBC (ANC / Platelets / Hgb)'],
    ['fevreNeutropenia', 'Febrile Neutropenia Episodes'],
    ['transfusionNeeds', 'Transfusion Requirements'],
    ['centralLine', 'Central Line / Port Present'],
  ],

  'Pediatric Nephrology': [
    ['ageOfChild', 'Age of Child'],
    ['renalCondition', 'Renal Condition'],
    ['urinalysis', 'Urinalysis Findings'],
    ['serumCreatinine', 'Serum Creatinine / eGFR'],
    ['urinaryProtein', 'Urine Protein (ACR)'],
    ['oedema', 'Oedema Present'],
    ['bp', 'Blood Pressure'],
    ['ultrasonography', 'Renal Ultrasound Findings'],
    ['steroids', 'Steroid Therapy'],
  ],

  'Adolescent Medicine': [
    ['age', 'Age'],
    ['pubertalStage', 'Pubertal Stage'],
    ['menstrualHistory', 'Menstrual History (if applicable)'],
    ['reproductiveHealth', 'Reproductive Health Concern'],
    ['substanceUse', 'Substance Use Screening'],
    ['mentalHealthScreen', 'Mental Health Screening (PHQ-A)'],
    ['schoolSocial', 'School / Social Functioning'],
    ['confidentiality', 'Confidentiality Discussion Done'],
  ],

  // ─── OBSTETRICS & GYNECOLOGY ──────────────────────────────────────────────
  'High-Risk Obstetrics': [
    ['gravida', 'Gravida / Para'],
    ['ga', 'Gestational Age (weeks)'],
    ['riskFactor', 'High-Risk Factor'],
    ['bp', 'Blood Pressure'],
    ['urinaryProtein', 'Urine Protein'],
    ['fetalMovements', 'Fetal Movements'],
    ['scanFindings', 'Growth Scan Findings'],
    ['hospitalAdmissions', 'Hospital Admissions This Pregnancy'],
    ['medications', 'Current Medications'],
  ],

  'Normal Obstetrics': [
    ['gravida', 'Gravida / Para'],
    ['ga', 'Gestational Age (weeks)'],
    ['lmp', 'LMP / EDD'],
    ['bp', 'Blood Pressure'],
    ['fetalHeartRate', 'Fetal Heart Rate (bpm)'],
    ['fetalPresentation', 'Fetal Presentation'],
    ['antenatalTests', 'Antenatal Tests Done'],
    ['supplementsTaken', 'Supplements (Iron / Folic Acid)'],
  ],

  'Reproductive Medicine': [
    ['infertilityDuration', 'Duration of Infertility (Years)'],
    ['infertilityType', 'Primary / Secondary'],
    ['semenAnalysis', 'Semen Analysis Results'],
    ['ovarianReserve', 'Ovarian Reserve (AMH / AFC)'],
    ['tubalPatency', 'Tubal Patency Test'],
    ['previousART', 'Previous ART Cycles'],
    ['diagnosis', 'Infertility Diagnosis'],
    ['arvProtocol', 'Proposed ART Protocol'],
  ],

  'Gynecological Oncology': [
    ['cancerType', 'Cancer Type (Cervical / Ovarian / Uterine)'],
    ['figo', 'FIGO Stage'],
    ['histology', 'Histology Report'],
    ['surgeryDone', 'Surgery Performed'],
    ['chemoCycle', 'Chemo Cycle & Regimen'],
    ['radiotherapy', 'Radiotherapy Given'],
    ['tumorMarker', 'Tumor Marker (CA-125 / CEA)'],
    ['imagingFindings', 'CT / PET Imaging Findings'],
  ],

  'Laparoscopic Gynecology': [
    ['indication', 'Indication for Laparoscopy'],
    ['endometriosis', 'Endometriosis Stage'],
    ['fibroidCount', 'Fibroid Count & Size'],
    ['ovarianCyst', 'Ovarian Cyst Details'],
    ['adhesions', 'Adhesions / Pelvic Pathology'],
    ['procedureDone', 'Procedure Performed'],
    ['intraopFindings', 'Intraoperative Findings'],
    ['postopPlan', 'Post-op Hormonal Plan'],
  ],

  Urogynaecology: [
    ['incontinenceType', 'Incontinence Type (Stress / Urge / Mixed)'],
    ['prolapsGrade', 'Prolapse Grade (POP-Q)'],
    ['leakageFrequency', 'Leakage Episodes / Day'],
    ['urodynamics', 'Urodynamics Result'],
    ['pelvisFloorEx', 'Pelvic Floor Exercise Compliance'],
    ['pessaryUse', 'Pessary In Situ'],
    ['previousSurgery', 'Previous Prolapse / Incontinence Surgery'],
    ['bowelSymptoms', 'Bowel Symptoms'],
  ],

  'Menopause Clinic': [
    ['lmp', 'Last Menstrual Period'],
    ['menopausalStatus', 'Menopausal Status (Peri / Post)'],
    ['hotFlushes', 'Hot Flushes (Frequency / Severity)'],
    ['nightSweats', 'Night Sweats'],
    ['urogenitalSymptoms', 'Urogenital Symptoms'],
    ['boneHealth', 'Bone Health (DEXA / T-score)'],
    ['hrtUsed', 'HRT Type & Duration'],
    ['cardiovascularRisk', 'Cardiovascular Risk Factors'],
  ],

  'Adolescent Gynecology': [
    ['age', 'Age'],
    ['pubertalStage', 'Pubertal Stage (Tanner)'],
    ['lmp', 'LMP'],
    ['cycleRegularity', 'Cycle Regularity'],
    ['dysmenorrhea', 'Dysmenorrhoea Severity (VAS)'],
    ['contraceptionNeeds', 'Contraception Discussion'],
    ['endoSuspicion', 'Endometriosis Suspicion'],
    ['sexuallyActive', 'Sexually Active (Confidential)'],
  ],

  'Fetal Medicine': [
    ['ga', 'Gestational Age (weeks)'],
    ['fetalAnomaly', 'Fetal Anomaly Detected'],
    ['ntMeasurement', 'NT Measurement (mm)'],
    ['chromosomalTest', 'Chromosomal Test (NIPT / Amnio)'],
    ['growth', 'Fetal Growth (EFW)'],
    ['doppler', 'Doppler Findings'],
    ['amniotic', 'Amniotic Fluid Index (AFI)'],
    ['counsellingGiven', 'Counselling Provided'],
  ],

  'Colposcopy Clinic': [
    ['cervicalSmear', 'Cervical Smear Result'],
    ['hpvStatus', 'HPV Status'],
    ['colposcopyFindings', 'Colposcopy Findings'],
    ['cinGrade', 'CIN Grade'],
    ['biopsyResult', 'Biopsy Result'],
    ['procedureDone', 'Procedure (LLETZ / Cryotherapy)'],
    ['followUpInterval', 'Follow-Up Interval'],
  ],

  // ─── OPHTHALMOLOGY ────────────────────────────────────────────────────────
  'Cataract Surgery': [
    ['va', 'Visual Acuity (Unaided / Best Corrected)'],
    ['lensStatus', 'Lens Status (Grade of Cataract)'],
    ['iop', 'IOP (mmHg)'],
    ['biometry', 'IOL Biometry (Axial Length / K-Readings)'],
    ['iolPower', 'IOL Power Selected'],
    ['pupilResponse', 'Pupil Response'],
    ['comorbidEyeDisease', 'Comorbid Eye Disease'],
    ['anaesthesiaType', 'Anaesthesia Type (LA / GA)'],
  ],

  'Glaucoma Clinic': [
    ['iop', 'IOP (mmHg)'],
    ['glaucomaType', 'Glaucoma Type (POAG / ACG / NTG)'],
    ['cdRatio', 'C:D Ratio'],
    ['visualField', 'Visual Field (Mean Deviation dB)'],
    ['rnfl', 'RNFL Thickness (OCT)'],
    ['iopMeds', 'Current IOP-Lowering Medications'],
    ['laserHistory', 'Laser History (SLT / LPI)'],
    ['surgeryDone', 'Glaucoma Surgery (Trab / Tube)'],
  ],

  'Retina & Vitreous': [
    ['condition', 'Retinal Condition'],
    ['va', 'Visual Acuity'],
    ['fundusFindings', 'Fundus Findings'],
    ['oct', 'OCT Findings'],
    ['ffa', 'FFA Findings'],
    ['antiVegf', 'Anti-VEGF Injections (Number / Last Date)'],
    ['laserDone', 'Laser Treatment Done'],
    ['surgeryHistory', 'Vitreoretinal Surgery History'],
  ],

  'Cornea & External Eye': [
    ['corneaCondition', 'Corneal Condition'],
    ['va', 'Visual Acuity'],
    ['slitLamp', 'Slit Lamp Findings'],
    ['schirmerTest', 'Schirmer Test (mm)'],
    ['topography', 'Corneal Topography'],
    ['graftStatus', 'Graft Status (if transplant)'],
    ['contactLensUse', 'Contact Lens Use'],
    ['dryEyeMeds', 'Dry Eye / Lubricant Drops'],
  ],

  'Pediatric Ophthalmology': [
    ['childAge', 'Age of Child'],
    ['squintType', 'Squint Type (Esotropia / Exotropia)'],
    ['prismCover', 'Prism Cover Test Deviation'],
    ['amblyopia', 'Amblyopia Present'],
    ['patchingCompliance', 'Patching Compliance'],
    ['refraction', 'Refraction Under Cycloplegia'],
    ['spectacles', 'Spectacles Prescribed'],
    ['surgeryDone', 'Strabismus Surgery Done'],
  ],

  Oculoplasty: [
    ['oculoplasticCondition', 'Condition (Ptosis / Entropion / Lesion)'],
    ['side', 'Side Affected'],
    ['mrd1', 'MRD-1 (mm)'],
    ['levatorFunction', 'Levator Function (mm)'],
    ['lacriSystem', 'Lacrimal System Involvement'],
    ['orbitImaging', 'CT Orbit Findings'],
    ['procedurePlanned', 'Procedure Planned'],
    ['cosmesisRequest', 'Cosmesis Concern'],
  ],

  'Refractive Surgery': [
    ['refractionSphere', 'Sphere (Diopters)'],
    ['refractionCylinder', 'Cylinder / Axis'],
    ['corneaThickness', 'Corneal Thickness (microns)'],
    ['keratoconusClear', 'Keratoconus Ruled Out'],
    ['pupilSize', 'Scotopic Pupil Size (mm)'],
    ['procedurePlanned', 'Procedure Planned (LASIK / LASEK / ICL)'],
    ['spectaclePower', 'Current Spectacle / CL Power'],
    ['screeningResult', 'Pre-op Screening Result'],
  ],

  'Uvea Clinic': [
    ['uveitisType', 'Uveitis Type (Anterior / Posterior / Pan)'],
    ['activity', 'Disease Activity (Active / Inactive)'],
    ['aetiology', 'Aetiology (Idiopathic / Sarcoid / HLA-B27)'],
    ['vision', 'Vision (LogMAR)'],
    ['kp', 'KP / Flare / Cells'],
    ['topicalSteroids', 'Topical Steroids Used'],
    ['systemic', 'Systemic Immunosuppression'],
    ['complications', 'Ocular Complications (CMO / Cataract)'],
  ],

  'Low Vision Clinic': [
    ['cause', 'Cause of Visual Impairment'],
    ['bvca', 'Best Corrected VA (Both Eyes)'],
    ['visualField', 'Visual Field Status'],
    ['lvaDevice', 'LVA Device Prescribed'],
    ['readingGoal', 'Reading / Activity Goal'],
    ['occupation', 'Occupation / School Status'],
    ['orientation', 'Orientation & Mobility Training'],
    ['supportNeeds', 'Assistive Technology Needs'],
  ],

  // ─── ENT ──────────────────────────────────────────────────────────────────
  Otology: [
    ['earComplaint', 'Ear Complaint'],
    ['side', 'Side Affected'],
    ['hearingLossType', 'Hearing Loss Type (Conductive / SNHL)'],
    ['audiogram', 'Audiogram Result (PTA)'],
    ['tinitus', 'Tinnitus Present'],
    ['vertigo', 'Vertigo / Dizziness'],
    ['perforationPresent', 'TM Perforation Present'],
    ['discharge', 'Ear Discharge'],
    ['surgeryHistory', 'Previous Ear Surgery'],
  ],

  Rhinology: [
    ['nasalComplaint', 'Nasal Complaint'],
    ['blockage', 'Nasal Blockage (Side / Severity)'],
    ['discharge', 'Nasal Discharge (Type)'],
    ['sinusSymptoms', 'Sinus Symptoms'],
    ['polyps', 'Nasal Polyps'],
    ['ctSinuses', 'CT Sinus Score (LM Score)'],
    ['allergyTest', 'Allergy Test Result'],
    ['functionalEndoscopy', 'FESS History'],
  ],

  Laryngology: [
    ['voiceComplaint', 'Voice Complaint'],
    ['hoarsenessDuration', 'Duration of Hoarseness'],
    ['videostroboscopy', 'Videostroboscopy Findings'],
    ['vocalCordStatus', 'Vocal Cord Status (Paralysis / Polyp)'],
    ['voiceAbuse', 'Voice Abuse / Professional Voice User'],
    ['reflux', 'Laryngopharyngeal Reflux (LPR)'],
    ['voiceTherapy', 'Voice Therapy History'],
    ['phonosurgery', 'Phonosurgery Planned'],
  ],

  'Head & Neck Surgery': [
    ['massLocation', 'Mass Location'],
    ['duration', 'Duration of Mass'],
    ['consistency', 'Consistency (Soft / Hard / Cystic)'],
    ['fnac', 'FNAC / Core Biopsy Result'],
    ['ctMri', 'CT / MRI Findings'],
    ['thyroidLump', 'Thyroid Lump (TI-RADS)'],
    ['lymphNode', 'Lymph Node Level'],
    ['surgeryPlanned', 'Surgery Planned'],
  ],

  'Pediatric ENT': [
    ['childAge', 'Age of Child'],
    ['condition', 'Condition (Tonsil / Adenoid / Ear Tubes)'],
    ['snoring', 'Snoring / Sleep Apnea'],
    ['reccurentTonsillitis', 'Recurrent Tonsillitis (Frequency)'],
    ['glueEar', 'Glue Ear / OME'],
    ['audiogram', 'Hearing Test Result'],
    ['surgical', 'Surgery Planned (AT / Grommets)'],
    ['growthConcern', 'Growth / Feeding Concern'],
  ],

  'Cochlear Implant': [
    ['hearingLossType', 'Hearing Loss Type'],
    ['audioResult', 'PTA / Aided Thresholds'],
    ['pta', 'Unaided PTA (dB HL)'],
    ['speechScore', 'Speech Discrimination Score'],
    ['ci', 'CI Device Selected'],
    ['mappingSession', 'Mapping Session Number'],
    ['rehabilitation', 'Auditory Verbal Therapy Progress'],
    ['mri', 'MRI Temporal Bone Findings'],
  ],

  'Skull Base Surgery': [
    ['tumor', 'Tumor Type / Location'],
    ['mriFindings', 'MRI / CT Skull Base Findings'],
    ['cranialNerveInvolvement', 'Cranial Nerve Involvement'],
    ['csfLeak', 'CSF Leak Present'],
    ['approachPlanned', 'Surgical Approach Planned'],
    ['radiotherapy', 'Adjuvant Radiotherapy'],
    ['teamDecision', 'Multidisciplinary Team Decision'],
  ],

  'Facial Plastics': [
    ['procedure', 'Procedure Planned (Rhinoplasty / Otoplasty)'],
    ['aestheticConcern', 'Aesthetic Concern'],
    ['postTrauma', 'Post-Traumatic / Post-Surgical'],
    ['skinType', 'Skin Type'],
    ['photoAnalysis', 'Photo Analysis Done'],
    ['expectationsDiscussed', 'Expectations Discussed'],
    ['anaesthesia', 'Anaesthesia Type'],
  ],

  'Snoring & Sleep Apnea': [
    ['ess', 'Epworth Sleepiness Scale'],
    ['psg', 'PSG / Home Sleep Test Result'],
    ['ahi', 'AHI (Events / Hour)'],
    ['oxygenNadir', 'Oxygen Nadir (%)'],
    ['cpapCompliance', 'CPAP Compliance (Hours / Night)'],
    ['surgicalOption', 'Surgical Option (UPPP / Coblation)'],
    ['mandibularDevice', 'Mandibular Advancement Device'],
    ['weightBmi', 'Weight / BMI'],
  ],

  'Allergy & Immunology-ENT': [
    ['allergenSkin', 'Skin Prick Test Result'],
    ['specificIge', 'Specific IgE Panel'],
    ['rhinitisType', 'Rhinitis Type (Allergic / Non-Allergic)'],
    ['immunotherapy', 'Immunotherapy Protocol'],
    ['avoidance', 'Allergen Avoidance Measures'],
    ['antihistamines', 'Current Antihistamines / INS'],
    ['sensitisationProfile', 'Sensitisation Profile'],
  ],

  // ─── DERMATOLOGY ──────────────────────────────────────────────────────────
  'Medical Dermatology': [
    ['skinCondition', 'Skin Condition'],
    ['bodyAreaAffected', 'Body Area Affected'],
    ['severity', 'Severity (Mild / Moderate / Severe)'],
    ['bsa', 'BSA / PASI / EASI Score'],
    ['itching', 'Pruritus Score (1–10)'],
    ['triggers', 'Triggers'],
    ['topicalTherapy', 'Current Topical Therapy'],
    ['systemic', 'Systemic / Biologic Therapy'],
    ['skinBiopsy', 'Skin Biopsy Result'],
  ],

  'Surgical Dermatology': [
    ['lesionType', 'Lesion Type'],
    ['lesionSize', 'Size (cm)'],
    ['location', 'Location on Body'],
    ['malignancySuspicion', 'Malignancy Suspicion (Low / High)'],
    ['dermoscopy', 'Dermoscopy Findings'],
    ['procedurePlanned', 'Procedure (Excision / Shave / MOHS)'],
    ['histopathology', 'Histopathology Result'],
    ['marginsStatus', 'Surgical Margins Status'],
  ],

  'Cosmetic Dermatology': [
    ['cosmeticConcern', 'Cosmetic Concern'],
    ['procedurePlanned', 'Procedure Planned'],
    ['skinType', 'Fitzpatrick Skin Type'],
    ['previousProcedure', 'Previous Cosmetic Procedures'],
    ['botoxArea', 'Botox Target Area'],
    ['fillerArea', 'Filler Target Area'],
    ['downtime', 'Acceptable Downtime'],
    ['expectations', 'Patient Expectations Discussed'],
  ],

  Trichology: [
    ['hairLossPattern', 'Hair Loss Pattern (AGA / DEEM / Patchy)'],
    ['onset', 'Onset & Duration'],
    ['hairPullTest', 'Hair Pull Test Result'],
    ['dermoscopy', 'Trichoscopy / Dermoscopy Findings'],
    ['serumFerritin', 'Serum Ferritin / Thyroid / CBC'],
    ['trichogramResult', 'Trichogram Result'],
    ['minoxidil', 'Minoxidil Use'],
    ['treatment', 'Other Treatment (Finasteride / PRP / HL)'],
  ],

  'Nail Disorders': [
    ['nailComplaint', 'Nail Complaint'],
    ['nailsAffected', 'Nails Affected'],
    ['koh', 'KOH Mount / Culture Result'],
    ['psoriaticNail', 'Psoriatic Nail Changes (Pitting / Onycholysis)'],
    ['onychomycosis', 'Onychomycosis Severity'],
    ['antifungal', 'Antifungal Therapy'],
    ['surgicalNail', 'Nail Surgery Planned'],
  ],

  'Pediatric Dermatology': [
    ['childAge', 'Age of Child'],
    ['condition', 'Skin Condition'],
    ['atopicScore', 'SCORAD / IGA Score (if Atopic)'],
    ['emollientUse', 'Emollient Use'],
    ['topicalSteroid', 'Topical Corticosteroid Strength & Frequency'],
    ['tacrolimus', 'Tacrolimus / Pimecrolimus Use'],
    ['infectiousTrigger', 'Infectious Trigger'],
    ['parentalCompliance', 'Parental Compliance / Education'],
  ],

  Phototherapy: [
    ['indication', 'Indication (Psoriasis / Vitiligo / MF)'],
    ['bodyArea', 'Body Area Treated'],
    ['nbUvbDose', 'NB-UVB Starting Dose (mJ/cm²)'],
    ['sessionNumber', 'Session Number'],
    ['response', 'Treatment Response (% Improvement)'],
    ['sideEffects', 'Side Effects (Erythema / Burn)'],
    ['maintenance', 'Maintenance Schedule'],
  ],

  'Sexually Transmitted Infections': [
    ['stiComplaint', 'STI-Related Complaint'],
    ['sexualHistory', 'Sexual History (Partners / Risk Behaviour)'],
    ['hivStatus', 'HIV Status & Last Test'],
    ['screeningTests', 'STI Screening Panel Done'],
    ['treatmentGiven', 'Treatment Given'],
    ['partnerNotification', 'Partner Notification Done'],
    ['prepPep', 'PrEP / PEP Counselled'],
  ],

  'Wound Care': [
    ['woundType', 'Wound Type (Venous / Arterial / Diabetic / Pressure)'],
    ['woundSize', 'Wound Size (cm × cm)'],
    ['woundBed', 'Wound Bed (Slough / Granulation / Eschar)'],
    ['exudate', 'Exudate Level & Type'],
    ['infectionSigns', 'Signs of Infection (NERDS / STONES)'],
    ['dressing', 'Current Dressing Regimen'],
    ['offloading', 'Offloading Device'],
    ['abis', 'ABPI / Vascular Assessment'],
  ],

  'Allergy Skin Clinic': [
    ['contactAllergen', 'Suspected Contact Allergen'],
    ['patchTest', 'Patch Test Result (Day 2 / Day 4)'],
    ['occupationalExposure', 'Occupational Exposure'],
    ['avoidanceAdvice', 'Avoidance Advice Given'],
    ['skinBarrier', 'Skin Barrier Repair'],
    ['currentTopical', 'Current Topical Agents'],
  ],

  // ─── PSYCHIATRY ───────────────────────────────────────────────────────────
  'Adult Psychiatry': [
    ['diagnosis', 'Psychiatric Diagnosis'],
    ['mseSummary', 'MSE Summary (Appearance / Mood / Thought / Insight)'],
    ['riskAssessment', 'Risk Assessment (Self-Harm / Suicide / Violence)'],
    ['currentMeds', 'Current Psychiatric Medications'],
    ['compliance', 'Medication Compliance'],
    ['substanceUse', 'Substance Use (Alcohol / Drugs)'],
    ['hospitalisations', 'Psychiatric Hospitalisations History'],
    ['functioningLevel', 'GAF Score / Functioning Level'],
  ],

  'Child & Adolescent Psychiatry': [
    ['childAge', 'Age of Child'],
    ['referralReason', 'Referral Reason'],
    ['diagnosis', 'Diagnosis (ADHD / Conduct / Mood)'],
    ['schoolFunctioning', 'School / Academic Functioning'],
    ['familyDynamics', 'Family Dynamics & Support'],
    ['riskBehaviours', 'Risk Behaviours (Self-Harm / Aggression)'],
    ['currentMeds', 'Current Medications'],
    ['therapyType', 'Therapy Type & Progress'],
  ],

  'Addiction Medicine': [
    ['substanceType', 'Substance Type'],
    ['durationOfUse', 'Duration of Use'],
    ['lastUse', 'Last Use (Date)'],
    ['dependenceSeverity', 'Dependence Severity (Mild / Moderate / Severe)'],
    ['withdrawalSigns', 'Withdrawal Signs / Score (CIWA / COWS)'],
    ['substitutionTherapy', 'Substitution Therapy (Methadone / Buprenorphine)'],
    ['motivationStage', 'Motivational Stage (Prochaska)'],
    ['supportSystem', 'Social Support / Rehab Program'],
  ],

  'Geriatric Psychiatry': [
    ['ageOfPatient', 'Age of Patient'],
    ['diagnosis', 'Diagnosis (Dementia / Depression / Delirium)'],
    ['mmse', 'MMSE / MoCA Score'],
    ['behavioural', 'Behavioural and Psychological Symptoms (BPSD)'],
    ['carerStress', 'Carer Burden / Stress'],
    ['polypharmacy', 'Polypharmacy Review'],
    ['safeguarding', 'Safeguarding Concern'],
    ['cognitiveDrilldown', 'Cognitive Domain Affected'],
  ],

  'Forensic Psychiatry': [
    ['legalContext', 'Legal / Court Context'],
    ['offenceHistory', 'Offence History'],
    ['diagnosis', 'Psychiatric Diagnosis'],
    ['riskTool', 'Risk Assessment Tool (HCR-20 / PCL-R)'],
    ['capacityAssessment', 'Mental Capacity Assessment'],
    ['detentionStatus', 'Detention Status (MHA / Prison)'],
    ['treatmentPlan', 'Treatment / Rehabilitation Plan'],
  ],

  'Liaison Psychiatry': [
    ['referralWard', 'Referring Ward / Specialty'],
    ['referralReason', 'Reason for Referral'],
    ['cognitiveScreen', 'Cognitive Screen (4AT / AMT)'],
    ['deliriumPresent', 'Delirium Assessment'],
    ['capacityIssue', 'Capacity Concern'],
    ['mse', 'Brief MSE'],
    ['recommendation', 'Liaison Recommendation'],
  ],

  Psychotherapy: [
    ['therapyType', 'Therapy Type (CBT / DBT / Psychodynamic / Group)'],
    ['sessionNumber', 'Session Number'],
    ['presentingProblem', 'Presenting Problem'],
    ['goals', 'Therapy Goals'],
    ['phq9', 'PHQ-9 Score'],
    ['gad7', 'GAD-7 Score'],
    ['safetyPlan', 'Safety Plan in Place'],
    ['homeworkCompliance', 'Between-Session Homework'],
  ],

  Neuropsychiatry: [
    ['neuropsychDiagnosis', 'Neuropsychiatric Diagnosis'],
    ['etiologyBrain', 'Underlying Brain Condition'],
    ['mriEegFindings', 'MRI / EEG Findings'],
    ['cognitiveProfile', 'Neuropsychological Profile'],
    ['behavioural', 'Behavioural Manifestations'],
    ['medications', 'Current Neuro-Psychiatric Medications'],
    ['multidisciplinary', 'MDT Involvement'],
  ],

  'Sleep Psychiatry': [
    ['sleepComplaint', 'Sleep Complaint'],
    ['insomniaDuration', 'Duration of Insomnia'],
    ['isi', 'Insomnia Severity Index (ISI)'],
    ['sleepHygiene', 'Sleep Hygiene Assessment'],
    ['cbtI', 'CBT-I Progress'],
    ['hypnotics', 'Hypnotic Medication Use'],
    ['circadianIssue', 'Circadian Rhythm Disorder'],
    ['coexistingMH', 'Co-existing Mental Health Condition'],
  ],

  'Eating Disorders': [
    ['edDiagnosis', 'ED Diagnosis (AN / BN / BED)'],
    ['bmi', 'BMI'],
    ['ednos', 'Duration of Illness'],
    ['eatScale', 'EAT-26 / EDE-Q Score'],
    ['medicalComplications', 'Medical Complications (Electrolytes / Cardiac)'],
    ['mealPlan', 'Meal Plan Compliance'],
    ['hospitalisation', 'Hospitalisation History'],
    ['bodyImage', 'Body Image Disturbance'],
    ['motivation', 'Motivation for Recovery'],
  ],

  // ─── GASTROENTEROLOGY ─────────────────────────────────────────────────────
  'Therapeutic Endoscopy': [
    ['indication', 'Indication for Endoscopy'],
    ['procedure', 'Procedure (ERCP / Polypectomy / Stenting)'],
    ['sedation', 'Sedation Type'],
    ['intraopFindings', 'Intraoperative Findings'],
    ['sphincterotomy', 'Sphincterotomy Done'],
    ['stoneExtraction', 'Stone Extraction / Lithotripsy'],
    ['complications', 'Complications (Post-procedure)'],
    ['antibiotics', 'Prophylactic Antibiotics Given'],
  ],

  Hepatology: [
    ['liverDisease', 'Liver Disease (Cirrhosis / Hepatitis / NAFLD)'],
    ['etiology', 'Etiology (Viral / Alcohol / Metabolic / Autoimmune)'],
    ['childPugh', 'Child-Pugh Score'],
    ['meld', 'MELD Score'],
    ['lfts', 'LFTs (ALT / AST / Bili / Albumin)'],
    ['fibroscan', 'FibroScan / Liver Stiffness (kPa)'],
    ['varices', 'Varices (Grade / Prophylaxis)'],
    ['hccScreening', 'HCC Screening (AFP / USS)'],
  ],

  'Inflammatory Bowel Disease': [
    ['ibdType', 'IBD Type (Crohn / UC)'],
    ['diseaseExtent', 'Disease Extent / Location'],
    ['activity', 'Disease Activity (Harvey-Bradshaw / Mayo Score)'],
    ['colonoscopyFindings', 'Colonoscopy / Histology'],
    ['biologics', 'Biologic / Immunomodulator Therapy'],
    ['steroids', 'Steroid Requirement'],
    ['fdrug', 'Therapeutic Drug Monitoring (TDM)'],
    ['surgicalHistory', 'Surgical History (Bowel Resection)'],
  ],

  'Colorectal Disorders': [
    ['colorectalComplaint', 'Colorectal Complaint'],
    ['rectalBleeding', 'Rectal Bleeding (Type / Frequency)'],
    ['hemorrhoidGrade', 'Haemorrhoid Grade'],
    ['analFissure', 'Anal Fissure Present'],
    ['colonoscopy', 'Colonoscopy Findings'],
    ['procedure', 'Procedure (Banding / Fissurectomy)'],
    ['constipation', 'Constipation / Bowel Habits'],
    ['cancerScreening', 'Colorectal Cancer Screening'],
  ],

  'Pancreatic Disease': [
    ['pancreasCondition', 'Pancreatic Condition'],
    ['amylaseLipase', 'Amylase / Lipase Level'],
    ['ctMri', 'CT / MRI Pancreas Findings'],
    ['duct', 'Pancreatic Duct Dilation'],
    ['exocrineFunction', 'Exocrine Insufficiency (Steatorrhoea / FE-1)'],
    ['endocrine', 'Endocrine Insufficiency (Diabetes)'],
    ['etiology', 'Etiology (Alcohol / Gallstone / Idiopathic)'],
    ['ercp', 'ERCP Required'],
  ],

  'Motility Clinic': [
    ['motilityCondition', 'Motility Condition'],
    ['dysphagia', 'Dysphagia (Solid / Liquid / Both)'],
    ['gerdSymptoms', 'GERD Symptoms (Frequency / Severity)'],
    ['manometry', 'Oesophageal Manometry Result'],
    ['phImpedance', '24h pH-Impedance Result'],
    ['ppi', 'PPI Dose & Response'],
    ['achalasiaScore', 'Eckardt Score (if Achalasia)'],
    ['treatmentPlanned', 'Treatment Planned (Dilation / POEM / Fundoplication)'],
  ],

  'GI Oncology': [
    ['cancerSite', 'GI Cancer Site'],
    ['stage', 'TNM Stage'],
    ['histology', 'Histology & Grade'],
    ['surgery', 'Surgery Performed'],
    ['chemoProtocol', 'Chemotherapy Protocol'],
    ['targetedTherapy', 'Targeted / Immunotherapy'],
    ['nutritionStatus', 'Nutritional Status'],
    ['palliative', 'Palliative / Curative Intent'],
  ],

  'Nutrition & Dietetics-GI': [
    ['nutritionalDiagnosis', 'Nutritional Diagnosis'],
    ['bmz', 'BMI / Weight History'],
    ['malabsorption', 'Malabsorption Syndrome'],
    ['dietaryHistory', '24h Dietary Recall'],
    ['supplementation', 'Oral / Enteral Supplementation'],
    ['parenteralNutrition', 'Parenteral Nutrition Required'],
    ['must', 'MUST / NRS-2002 Score'],
    ['dietary', 'Dietary Advice Given'],
  ],

  'Capsule Endoscopy': [
    ['indication', 'Indication'],
    ['smallBowelFindings', 'Small Bowel Findings'],
    ['bleedingSource', 'Obscure GI Bleed Source Identified'],
    ['polyps', 'Polyps / Lesions Found'],
    ['transitTime', 'Gastric / Small Bowel Transit Time (hrs)'],
    ['completionRate', 'Capsule Reached Colon'],
    ['retentionRisk', 'Retention Risk (Patency Capsule Used)'],
  ],

  // ─── UROLOGY ──────────────────────────────────────────────────────────────
  'Urological Oncology': [
    ['cancerType', 'Cancer Type (Prostate / Bladder / Kidney)'],
    ['stage', 'TNM Stage'],
    ['psa', 'PSA Level (if Prostate)'],
    ['gleasonScore', 'Gleason Score / Grade Group'],
    ['surgery', 'Surgery Performed'],
    ['adjuvantTherapy', 'Adjuvant / Hormonal Therapy'],
    ['imagingFindings', 'CT / MRI / PET Findings'],
    ['surveillance', 'Surveillance Protocol'],
  ],

  Endourology: [
    ['stoneLocation', 'Stone Location (Ureter / Kidney / Bladder)'],
    ['stoneSize', 'Stone Size (mm)'],
    ['stoneComposition', 'Stone Composition (if known)'],
    ['uretvarsconomy', 'Ureteroscopy / PCNL Result'],
    ['urine', 'Urine Culture'],
    ['metabolicWorkup', 'Metabolic Stone Workup'],
    ['jjStent', 'JJ Stent Placed'],
    ['shockwave', 'ESWL Done'],
  ],

  'Laparoscopic Urology': [
    ['procedure', 'Procedure (Nephrectomy / Pyeloplasty / Ureteroplasty)'],
    ['indication', 'Indication'],
    ['renal', 'Renal Function (eGFR)'],
    ['imagingFindings', 'CT / MRI Findings'],
    ['intraop', 'Intraoperative Findings'],
    ['conversion', 'Conversion to Open (if any)'],
    ['postopCourse', 'Post-operative Course'],
  ],

  Andrology: [
    ['complaint', 'Chief Complaint (Infertility / ED / Hypogonadism)'],
    ['semenAnalysis', 'Semen Analysis (WHO Criteria)'],
    ['testosterone', 'Total Testosterone Level'],
    ['lhFsh', 'LH / FSH'],
    ['prolactin', 'Prolactin Level'],
    ['scrotalUltrasound', 'Scrotal Ultrasound Findings'],
    ['sexualHistory', 'Sexual & Ejaculatory History'],
    ['treatment', 'Treatment (IUI / ICSI / T-Therapy)'],
  ],

  'Pediatric Urology': [
    ['childAge', 'Age of Child'],
    ['urologyCondition', 'Condition (UTD / Hypospadias / UDT)'],
    ['urinalysis', 'Urinalysis / Culture'],
    ['renalUltrasound', 'Renal / Bladder Ultrasound'],
    ['vcug', 'VCUG Findings'],
    ['surgery', 'Surgery Planned'],
    ['followup', 'Follow-Up Plan (Renal Function / Scan)'],
  ],

  'Female Urology': [
    ['complaint', 'Complaint (Incontinence / Prolapse / UTI)'],
    ['utiFrequency', 'UTI Frequency (Recurrent)'],
    ['incontinenceType', 'Incontinence Type'],
    ['pad', 'Pad Usage (Number / Type)'],
    ['urodynamics', 'Urodynamics Result'],
    ['pelvicFloor', 'Pelvic Floor Exercise History'],
    ['surgery', 'Previous Prolapse / Incontinence Surgery'],
    ['oestrogen', 'Vaginal Oestrogen Use'],
  ],

  Neurourology: [
    ['neurologicalCondition', 'Neurological Condition'],
    ['bladderDysfunction', 'Bladder Dysfunction Type (DH / UAB / DSD)'],
    ['urodynamics', 'Video Urodynamics Result'],
    ['uscatheterization', 'Intermittent Self-Catheterization'],
    ['anticholinergics', 'Anticholinergic / Beta-3 Agonist Therapy'],
    ['botox', 'Botox Injection (Bladder)'],
    ['renalProtection', 'Upper Tract Protection Status'],
  ],

  'Reconstructive Urology': [
    ['condition', 'Condition (Stricture / Fistula / Trauma)'],
    ['strictureLength', 'Urethral Stricture Length & Location'],
    ['rgu', 'RGU / MCU Findings'],
    ['previousSurgery', 'Previous Urethral Surgery'],
    ['graft', 'Graft / Flap Used'],
    ['flowRate', 'Uroflowmetry Result'],
    ['pvr', 'Post-Void Residual (ml)'],
  ],

  'BPH Clinic': [
    ['ipssScore', 'IPSS Score'],
    ['psa', 'PSA Level'],
    ['prostate', 'Prostate Volume (USS / TRUS)'],
    ['pvr', 'Post-Void Residual (ml)'],
    ['uroflow', 'Qmax (ml/s)'],
    ['alphaBlocker', 'Alpha-Blocker Therapy'],
    ['5ari', '5-Alpha Reductase Inhibitor'],
    ['surgery', 'Surgical Option (TURP / HoLEP / UroLift)'],
  ],

  'Robotic Urology': [
    ['procedure', 'Robotic Procedure (RARP / RPN / RPy)'],
    ['dockingTime', 'Robot Docking Time (min)'],
    ['consoleTime', 'Console Time (min)'],
    ['bloodLoss', 'Estimated Blood Loss (ml)'],
    ['nerveSpar', 'Nerve-Sparing Performed'],
    ['surgicalMargins', 'Surgical Margin Status (PSM)'],
    ['postopIncontinence', 'Post-op Continence Status'],
    ['erectileFunction', 'Erectile Function Recovery'],
  ],

  // ─── ONCOLOGY ─────────────────────────────────────────────────────────────
  'Medical Oncology': [
    ['cancerDiagnosis', 'Cancer Diagnosis'],
    ['stage', 'TNM Stage'],
    ['histology', 'Histology & Grade'],
    ['biomarkers', 'Biomarkers (HER2 / KRAS / PD-L1 / EGFR)'],
    ['chemoCycle', 'Chemotherapy Cycle & Protocol'],
    ['targetedTherapy', 'Targeted Therapy / Immunotherapy'],
    ['toxicity', 'Treatment Toxicity (Grade)'],
    ['ecogPerformance', 'ECOG Performance Status'],
  ],

  'Radiation Oncology': [
    ['cancerSite', 'Cancer Site'],
    ['rtTechnique', 'RT Technique (3DCRT / IMRT / SBRT / VMAT)'],
    ['totalDose', 'Total Dose (Gy)'],
    ['fractionation', 'Fractionation Schedule'],
    ['targetVolume', 'Target Volume (GTV / CTV / PTV)'],
    ['criticalOrgans', 'Critical Organ Doses'],
    ['acuteReactions', 'Acute Radiation Reactions'],
    ['intent', 'Intent (Curative / Palliative)'],
  ],

  'Surgical Oncology': [
    ['cancerSite', 'Cancer Site'],
    ['surgeryType', 'Surgery Type'],
    ['resectionMargins', 'Resection Margin Status (R0/R1/R2)'],
    ['lymphNodeHarvest', 'Lymph Node Harvest / Positive Nodes'],
    ['reconstruction', 'Reconstruction Performed'],
    ['neo', 'Neoadjuvant Therapy Given'],
    ['histopathology', 'Final Histopathology'],
    ['adjuvantPlan', 'Adjuvant Therapy Plan'],
  ],

  'Breast Oncology': [
    ['breastDiagnosis', 'Diagnosis (IDC / ILC / DCIS)'],
    ['stage', 'TNM Stage'],
    ['grade', 'Histological Grade'],
    ['hormone', 'ER / PR / HER2 Status'],
    ['surgery', 'Surgery (WLE / Mastectomy / SLNB / ALND)'],
    ['chemotherapy', 'Chemotherapy Regimen'],
    ['hormonal', 'Endocrine Therapy (Tamoxifen / AI)'],
    ['geneticTest', 'BRCA1/2 Testing'],
  ],

  'Thoracic Oncology': [
    ['lungCancer', 'Cancer Type (NSCLC / SCLC / Mesothelioma)'],
    ['stage', 'Stage'],
    ['mutationStatus', 'Mutation Status (EGFR / ALK / ROS1 / KRAS)'],
    ['pdl1', 'PD-L1 Expression (%)'],
    ['surgery', 'Surgery Performed (Lobectomy / Pneumonectomy)'],
    ['chemotherapy', 'Chemotherapy Protocol'],
    ['immunotherapy', 'Immunotherapy Agent'],
    ['spirometry', 'Pre-treatment Spirometry'],
  ],

  'Neuro-Oncology': [
    ['tumorType', 'Tumor Type (Glioma / Meningioma / Metastasis)'],
    ['who', 'WHO Grade'],
    ['molecularMarkers', 'IDH / MGMT / 1p/19q Status'],
    ['mriFindings', 'MRI Brain Findings'],
    ['kpsScore', 'KPS Score'],
    ['surgery', 'Surgery (Extent of Resection)'],
    ['stupp', 'Stupp Protocol / Temozolomide'],
    ['seizures', 'Seizure Management'],
  ],

  'Hematological Oncology': [
    ['hemDiagnosis', 'Hematological Diagnosis (AML / ALL / NHL / MM)'],
    ['stage', 'Stage / Risk Stratification'],
    ['cbc', 'CBC with Differential'],
    ['boneMorrow', 'Bone Marrow Biopsy Result'],
    ['cytogenetics', 'Cytogenetics / FISH'],
    ['induction', 'Induction Chemotherapy Protocol'],
    ['transplant', 'Stem Cell Transplant (ASCT / Allo)'],
    ['transfusion', 'Transfusion Support'],
  ],

  'Palliative Oncology': [
    ['cancerDiagnosis', 'Cancer Diagnosis'],
    ['performance', 'Performance Status (ECOG / KPS)'],
    ['painScore', 'Pain Score (VAS / NRS)'],
    ['opioid', 'Opioid Analgesic & Dose'],
    ['nausea', 'Nausea / Vomiting Control'],
    ['breathlessness', 'Breathlessness Score'],
    ['goalsOfCare', 'Goals of Care Discussion'],
    ['advanceDirective', 'Advance Directive / DNR'],
  ],

  // ─── PULMONOLOGY ──────────────────────────────────────────────────────────
  'Asthma Clinic': [
    ['asthmaControl', 'Asthma Control (ACT / GINA Step)'],
    ['spirometry', 'Spirometry (FEV1 / FVC / BD Response)'],
    ['peakFlow', 'Peak Flow (Best / Diurnal Variation)'],
    ['reliever', 'Reliever Inhaler Use (Puffs / Week)'],
    ['ics', 'ICS / LABA Regimen'],
    ['triggerFactors', 'Trigger Factors'],
    ['hospitalisations', 'Hospitalisations / ER Visits (Last 12 Months)'],
    ['inhalerTechnique', 'Inhaler Technique Checked'],
  ],

  'COPD Clinic': [
    ['goldStage', 'GOLD Stage / Group (A/B/E)'],
    ['fev1', 'FEV1 (% Predicted)'],
    ['mMRC', 'mMRC Dyspnoea Score'],
    ['catScore', 'CAT Score'],
    ['exacerbations', 'Exacerbations (Last 12 Months)'],
    ['lama', 'LAMA / LABA / ICS Triple Therapy'],
    ['o2', 'Home Oxygen Requirement'],
    ['smokingStatus', 'Current Smoking Status'],
    ['pulmonaryRehab', 'Pulmonary Rehab Attendance'],
  ],

  'Interventional Pulmonology': [
    ['procedure', 'Procedure (Bronchoscopy / EBUS / Thoracentesis)'],
    ['indication', 'Indication'],
    ['airways', 'Airways Assessment'],
    ['lymphNode', 'EBUS-TBNA Lymph Node Station'],
    ['biopsyResult', 'Biopsy / BAL Result'],
    ['fluidAnalysis', 'Pleural Fluid Analysis'],
    ['stent', 'Airway Stent Placed'],
    ['complication', 'Post-procedure Complication'],
  ],

  'Interstitial Lung Disease': [
    ['ildType', 'ILD Type (UIP / NSIP / HP / Sarcoid)'],
    ['hrct', 'HRCT Findings (Pattern)'],
    ['dlco', 'DLCO (% Predicted)'],
    ['fvc', 'FVC (% Predicted)'],
    ['ctd', 'Associated CTD'],
    ['antifibrotic', 'Antifibrotic Therapy (Pirfenidone / Nintedanib)'],
    ['oxygen', 'Ambulatory O₂ Requirement'],
    ['transplantList', 'Lung Transplant Evaluation'],
  ],

  'Tuberculosis Clinic': [
    ['tbType', 'TB Type (Pulmonary / Extrapulmonary / DR-TB)'],
    ['sputumSmear', 'Sputum Smear / Culture Result'],
    ['geneXpert', 'GeneXpert Result'],
    ['dst', 'Drug Susceptibility Testing'],
    ['treatment', 'Current DOTS Regimen'],
    ['monthOfTherapy', 'Month of Therapy'],
    ['adherence', 'DOT Adherence'],
    ['hivCoinfection', 'HIV Co-infection Status'],
  ],

  'Sleep & Respiratory': [
    ['apneaType', 'Sleep Apnea Type (OSA / CSA)'],
    ['ahi', 'AHI (Events / Hour)'],
    ['o2Nadir', 'O₂ Nadir (%)'],
    ['cpapMode', 'CPAP / BiPAP Mode & Pressure'],
    ['cpapCompliance', 'CPAP Compliance (Hrs / Night)'],
    ['residualAhi', 'Residual AHI on CPAP'],
    ['obesity', 'Obesity / Neck Circumference'],
    ['htn', 'Comorbid Hypertension / CVD'],
  ],

  'Pulmonary Hypertension': [
    ['pahGroup', 'PH Group (WHO Group 1–5)'],
    ['meanPap', 'Mean PAP (mmHg) on RHC'],
    ['pvr', 'PVR (Wood Units)'],
    ['whoFc', 'WHO Functional Class'],
    ['sixMwd', '6-Minute Walk Distance (m)'],
    ['pdeI', 'PDE-5 Inhibitor / ERA / Prostacyclin'],
    ['echoTrv', 'Echo: TRPG / RVSP'],
    ['ctdRelated', 'CTD-Related PH'],
  ],

  'Pleural Disease': [
    ['pleuralCondition', 'Pleural Condition (Effusion / Pneumothorax / Empyema)'],
    ['side', 'Side Affected'],
    ['amount', 'Amount (Small / Moderate / Large)'],
    ['fluidAnalysis', 'Pleural Fluid Analysis (Exudate / Transudate)'],
    ['ph', 'Pleural Fluid pH'],
    ['drainage', 'Drainage Done (Thoracentesis / ICD)'],
    ['pleurodesis', 'Pleurodesis Performed'],
    ['cause', 'Underlying Cause'],
  ],

  'Critical Care Pulmonology': [
    ['icu', 'ICU Admission Reason'],
    ['ventilator', 'Ventilator Mode (AC-VC / PSV / PRVC)'],
    ['fio2', 'FiO₂ / PEEP'],
    ['pf', 'P/F Ratio (ARDS Severity)'],
    ['lungProtective', 'Lung-Protective Ventilation Parameters'],
    ['proning', 'Proning Done'],
    ['vasopressors', 'Vasopressor Support'],
    ['weaning', 'Weaning Status / SBT Result'],
  ],

  'Lung Cancer Screening': [
    ['age', 'Age'],
    ['packYearHistory', 'Pack-Year Smoking History'],
    ['ldctResult', 'Low-Dose CT Result'],
    ['noduleSize', 'Nodule Size & Type (Solid / GGO)'],
    ['luRadsCategory', 'Lung-RADS Category'],
    ['followUpInterval', 'Follow-Up Interval'],
    ['counselling', 'Smoking Cessation Counselling'],
  ],

  // ─── ENDOCRINOLOGY ────────────────────────────────────────────────────────
  'Diabetes Mellitus': [
    ['diabetesType', 'Diabetes Type (1 / 2 / MODY / Gestational)'],
    ['hba1c', 'HbA1c (%)'],
    ['fastingBs', 'Fasting Blood Sugar (mg/dL)'],
    ['postprandialBs', 'Post-Prandial Blood Sugar (mg/dL)'],
    ['insulin', 'Insulin Regimen (Type / Dose)'],
    ['oha', 'Oral Hypoglycaemic Agents'],
    ['hypoglycemia', 'Hypoglycaemic Episodes'],
    ['complications', 'Microvascular / Macrovascular Complications'],
    ['cgm', 'CGM / Time in Range (%)'],
  ],

  'Thyroid Disorders': [
    ['condition', 'Condition (Hypo / Hyper / Nodule / Graves)'],
    ['tsh', 'TSH (mIU/L)'],
    ['ft4', 'Free T4 (pmol/L)'],
    ['tpoAntibody', 'TPO Antibody'],
    ['tshRAntibody', 'TSH-R Antibody (if Graves)'],
    ['thyroidUss', 'Thyroid Ultrasound (ACR TI-RADS)'],
    ['medications', 'Thyroxine / Carbimazole / Propranolol Dose'],
    ['radioiodine', 'Previous Radioiodine Treatment'],
  ],

  'Adrenal Disorders': [
    ['condition', 'Condition (Cushing / Addison / Pheo / Incidentaloma)'],
    ['cortisol', 'Morning Cortisol / ACTH Stimulation'],
    ['acth', 'Plasma ACTH'],
    ['aldosterone', 'Aldosterone / Renin Ratio'],
    ['catecholamines', '24h Urine Catecholamines (if Pheo)'],
    ['imagingFindings', 'CT / MRI Adrenal Findings'],
    ['replacement', 'Steroid Replacement Regimen'],
    ['sickDayRules', 'Sick Day Rules Counselled'],
  ],

  'Pituitary Disorders': [
    ['pituitaryCondition', 'Condition (Acromegaly / Prolactinoma / Panhypo)'],
    ['ghIgf1', 'GH / IGF-1 Level'],
    ['prolactin', 'Prolactin Level'],
    ['cortisol', 'Cortisol Axis (Basal / Dynamic Test)'],
    ['mriPituitary', 'MRI Pituitary Findings (Macro / Micro Adenoma)'],
    ['visualFields', 'Visual Field Assessment'],
    ['medications', 'Cabergoline / Octreotide / Hydrocortisone'],
    ['surgery', 'Trans-Sphenoidal Surgery History'],
  ],

  'Osteoporosis Clinic': [
    ['dexa', 'DEXA T-Score (Spine / Hip)'],
    ['frax', 'FRAX 10-Year Risk (%)'],
    ['vitaminD', 'Vitamin D Level (nmol/L)'],
    ['calcium', 'Serum Calcium'],
    ['pth', 'PTH Level'],
    ['fractureHistory', 'Fragility Fracture History'],
    ['bisphosphonate', 'Bisphosphonate / Denosumab Therapy'],
    ['fallsPrevention', 'Falls Prevention Programme'],
  ],

  'Obesity & Metabolic': [
    ['bmi', 'BMI (kg/m²)'],
    ['waist', 'Waist Circumference (cm)'],
    ['weightHistory', 'Weight Loss History'],
    ['metabolicSyndrome', 'Metabolic Syndrome Features'],
    ['gip', 'GLP-1 RA / Tirzepatide Therapy'],
    ['diet', 'Dietary Assessment (Calories / Macros)'],
    ['physicalActivity', 'Physical Activity (Minutes / Week)'],
    ['surgeryConsidered', 'Bariatric Surgery Considered'],
  ],

  'Reproductive Endocrinology': [
    ['condition', 'Condition (PCOS / Hypogonadism / Infertility)'],
    ['menstrualHistory', 'Menstrual History'],
    ['androgens', 'Testosterone / DHEAS / SHBG'],
    ['lhFsh', 'LH / FSH Ratio'],
    ['amh', 'AMH Level'],
    ['insulinResistance', 'Insulin Resistance (HOMA-IR)'],
    ['ovulationInduction', 'Ovulation Induction Protocol'],
    ['contraception', 'Hormonal Contraception Used'],
  ],

  'Pediatric Endocrinology': [
    ['childAge', 'Age of Child'],
    ['condition', 'Condition (GHD / T1DM / Precocious Puberty)'],
    ['heightSDS', 'Height SDS'],
    ['growthVelocity', 'Growth Velocity (cm/year)'],
    ['boneAge', 'Bone Age (Greulich-Pyle)'],
    ['ghStimulation', 'GH Stimulation Test Result'],
    ['pubertyStage', 'Tanner Stage'],
    ['treatment', 'GH / Insulin / Puberty Suppression Therapy'],
  ],

  'Lipid Clinic': [
    ['ldl', 'LDL-C (mmol/L)'],
    ['hdl', 'HDL-C (mmol/L)'],
    ['tg', 'Triglycerides (mmol/L)'],
    ['lipidDiagnosis', 'Lipid Diagnosis (FH / Mixed / Hypertriglyceridaemia)'],
    ['statinType', 'Statin Type & Dose'],
    ['ezetimibe', 'Ezetimibe Used'],
    ['pcsk9', 'PCSK9 Inhibitor'],
    ['cardiovascularRisk', 'Cardiovascular Risk (SCORE2 / FRS)'],
    ['statin', 'Statin Intolerance Documented'],
  ],

  Neuroendocrinology: [
    ['condition', 'Condition (Carcinoid / VIPoma / Hypothalamic Disorder)'],
    ['netMarkers', 'NET Markers (CgA / 5-HIAA / VIP)'],
    ['imagingFindings', 'CT / Dotatate PET Findings'],
    ['somatostatinAnalog', 'Somatostatin Analogue Therapy'],
    ['surgery', 'Surgery / Embolisation Done'],
    ['ssrs', 'Somatostatin Receptor Scintigraphy'],
  ],

  // ─── NEPHROLOGY ───────────────────────────────────────────────────────────
  'Chronic Kidney Disease': [
    ['ckdStage', 'CKD Stage (G1–G5)'],
    ['egfr', 'eGFR (ml/min/1.73m²)'],
    ['uacr', 'UACR (mg/g)'],
    ['bp', 'Blood Pressure Target'],
    ['proteinuria', 'Proteinuria (g/day)'],
    ['anemia', 'Anaemia (Hb / ESA Therapy)'],
    ['ckdMbd', 'CKD-MBD (Calcium / Phosphate / PTH / VitD)'],
    ['raas', 'RAAS Blockade Therapy'],
    ['progression', 'Progression Rate (eGFR Slope)'],
  ],

  Hemodialysis: [
    ['dialysisAccess', 'Dialysis Access (AVF / AVG / Permcath)'],
    ['ktv', 'Kt/V (Dialysis Adequacy)'],
    ['sessionFrequency', 'Sessions per Week'],
    ['ufVolume', 'UF Volume (L / Session)'],
    ['dryWeight', 'Estimated Dry Weight (kg)'],
    ['hemoglobin', 'Haemoglobin / ESA Dose'],
    ['pth', 'PTH Level'],
    ['bp', 'Intradialytic Blood Pressure'],
  ],

  'Peritoneal Dialysis': [
    ['pdType', 'PD Type (CAPD / APD)'],
    ['exchangeVolume', 'Exchange Volume (L)'],
    ['exchangeFreq', 'Number of Exchanges / Day'],
    ['peritoneFunction', 'Peritoneal Equilibration Test (PET)'],
    ['residualRenal', 'Residual Renal Function'],
    ['ultrafiltration', 'Ultrafiltration (ml / Day)'],
    ['peritonitis', 'Peritonitis Episodes (Last 12 Months)'],
    ['exitSite', 'Exit Site Condition'],
  ],

  'Renal Transplant': [
    ['transplantDate', 'Transplant Date'],
    ['donorType', 'Donor Type (Deceased / Living)'],
    ['calcineurin', 'Calcineurin Inhibitor Levels (Tacrolimus / CyA)'],
    ['rejectionEpisode', 'Rejection Episode (Type / Grade)'],
    ['dsaLevel', 'Donor-Specific Antibody (DSA)'],
    ['egfr', 'Post-Transplant eGFR'],
    ['cmvBk', 'CMV / BK Virus Status'],
    ['immunosuppression', 'Current Immunosuppression Regimen'],
  ],

  Glomerulonephritis: [
    ['gnType', 'GN Type (IgA / FSGS / MN / MPGN)'],
    ['biopsyResult', 'Renal Biopsy Result'],
    ['proteinuria', 'Proteinuria (g/day)'],
    ['egfr', 'eGFR'],
    ['complement', 'Complement Levels (C3 / C4)'],
    ['anca', 'ANCA / Anti-GBM / ANA'],
    ['immunosuppression', 'Immunosuppression Protocol'],
    ['remission', 'Remission Status'],
  ],

  'Hypertensive Nephropathy': [
    ['bp', 'Blood Pressure (Controlled / Uncontrolled)'],
    ['egfr', 'eGFR'],
    ['uacr', 'UACR'],
    ['raas', 'RAAS Blockade (ACEi / ARB)'],
    ['additionalBpMeds', 'Additional Antihypertensives'],
    ['targetBp', 'Target BP Achieved'],
    ['endOrganDamage', 'Other End-Organ Damage'],
  ],

  'Diabetic Nephropathy': [
    ['diabetesDuration', 'Diabetes Duration (Years)'],
    ['egfr', 'eGFR'],
    ['uacr', 'UACR (mg/g)'],
    ['hba1c', 'HbA1c (%)'],
    ['raas', 'RAAS Blockade Used'],
    ['sglt2', 'SGLT2 Inhibitor Used'],
    ['retinopathy', 'Co-existing Retinopathy'],
    ['progression', 'Decline in eGFR (ml/min/year)'],
  ],

  'Acute Kidney Injury': [
    ['akiStage', 'AKI Stage (KDIGO 1/2/3)'],
    ['baselineCreatinine', 'Baseline Creatinine'],
    ['currentCreatinine', 'Current Creatinine'],
    ['urineOutput', 'Urine Output (ml/kg/hr)'],
    ['cause', 'AKI Cause (Pre / Intra / Post Renal)'],
    ['fluid', 'Fluid Resuscitation Status'],
    ['rrt', 'RRT Required (CRRT / IHD)'],
    ['recovery', 'Renal Recovery Assessment'],
  ],

  'Interventional Nephrology': [
    ['procedure', 'Procedure (AVF / Permcath / Biopsy)'],
    ['indication', 'Indication'],
    ['accessSite', 'Access Site'],
    ['imagingGuide', 'Imaging Guidance Used'],
    ['complication', 'Procedural Complication'],
    ['postprocedure', 'Post-Procedure Assessment'],
  ],

  // ─── RHEUMATOLOGY ─────────────────────────────────────────────────────────
  'Rheumatoid Arthritis': [
    ['das28', 'DAS28 Score'],
    ['jointsSwollen', 'Swollen Joint Count'],
    ['jointsTender', 'Tender Joint Count'],
    ['rfAntiCcp', 'RF / Anti-CCP Status'],
    ['crpEsr', 'CRP / ESR'],
    ['dmard', 'Current DMARD (MTX / LEF / HCQ)'],
    ['biologic', 'Biologic / JAK Inhibitor'],
    ['xrayErosion', 'X-Ray Erosions'],
    ['treatTarget', 'Treat-to-Target (Remission / LDA)'],
  ],

  'Systemic Lupus Erythematosus': [
    ['sledai', 'SLEDAI Score'],
    ['organManifestations', 'Organ Manifestations (Renal / CNS / Skin / Joints)'],
    ['complement', 'Complement (C3 / C4)'],
    ['antidsDna', 'Anti-dsDNA Level'],
    ['hydroxychloroquine', 'Hydroxychloroquine Dose'],
    ['steroids', 'Current Steroid Dose (Prednisolone mg)'],
    ['immunosuppression', 'Immunosuppression (AZA / MMF / CYC)'],
    ['antiphospholipid', 'Antiphospholipid Antibodies'],
  ],

  Spondyloarthropathy: [
    ['spacer', 'Condition (AS / PsA / ReA / IBD-SpA)'],
    ['basdai', 'BASDAI Score'],
    ['asdas', 'ASDAS Score'],
    ['sacroilitis', 'Sacroiliitis on MRI / X-Ray'],
    ['hlaB27', 'HLA-B27 Status'],
    ['nsaids', 'NSAID Response'],
    ['biologic', 'Biologic (TNFi / IL-17i / IL-23i)'],
    ['psoriasis', 'Psoriasis Involvement'],
    ['ibd', 'IBD Co-morbidity'],
  ],

  Vasculitis: [
    ['vasculitisType', 'Vasculitis Type (GCA / ANCA / PAN / Behcet)'],
    ['bvas', 'BVAS / Vasculitis Damage Index'],
    ['anca', 'ANCA (MPO / PR3)'],
    ['organInvolvement', 'Organ Involvement'],
    ['pulmonaryRenal', 'Pulmonary-Renal Syndrome'],
    ['inductionTherapy', 'Induction Therapy (CYC / Rituximab)'],
    ['maintenanceTherapy', 'Maintenance Therapy (AZA / RTX)'],
    ['gca', 'GCA: Temporal Artery Biopsy / PET'],
  ],

  'Gout Clinic': [
    ['goutAttacks', 'Gout Attacks (Frequency / Joints)'],
    ['serumUrate', 'Serum Urate (Target < 0.36 mmol/L)'],
    ['urateTarget', 'Urate-Lowering Therapy (Allopurinol / Febuxostat)'],
    ['flareManagement', 'Flare Management (Colchicine / NSAIDs / Steroids)'],
    ['tophiPresent', 'Tophi Present'],
    ['diet', 'Dietary Counselling (Purine / Alcohol)'],
    ['diuretics', 'Diuretic Use (Gout Risk Factor)'],
  ],

  'Osteoporosis Rheumatology': [
    ['osteoporosisContext', 'Glucocorticoid-Induced Osteoporosis'],
    ['gioTherapy', 'GIO Prevention Therapy'],
    ['dexa', 'DEXA T-Score'],
    ['frax', 'FRAX Score'],
    ['vitaminD', 'Vitamin D Level'],
    ['antiresorptive', 'Antiresorptive Therapy'],
    ['sterosDose', 'Current Steroid Dose & Duration'],
  ],

  'Myositis Clinic': [
    ['myositisDx', 'Diagnosis (PM / DM / IBM / IMNM)'],
    ['cpk', 'CPK Level (U/L)'],
    ['antibodies', 'Myositis-Specific Antibodies (Anti-Jo-1 / Anti-MDA5)'],
    ['emgFindings', 'EMG Findings'],
    ['mri', 'MRI Muscle Findings'],
    ['biopsyResult', 'Muscle Biopsy Result'],
    ['immunosuppression', 'Immunosuppression Protocol'],
    ['ild', 'ILD Association'],
  ],

  'Sjogren Syndrome': [
    ['diagnosis', 'Primary / Secondary Sjogren'],
    ['schirmer', 'Schirmer Test (mm / 5 min)'],
    ['lipBiopsy', 'Minor Salivary Gland Biopsy (Focus Score)'],
    ['ssaSsb', 'Anti-SSA / Anti-SSB Antibodies'],
    ['esspriScore', 'ESSPRI Symptom Score'],
    ['essdaiScore', 'ESSDAI Disease Activity Score'],
    ['dryEyeTreatment', 'Dry Eye / Dry Mouth Management'],
    ['systemicManifestations', 'Systemic Manifestations'],
  ],

  'Fibromyalgia Clinic': [
    ['fibromyalgiaDx', 'ACR 2016 Diagnostic Criteria Met'],
    ['wpi', 'Widespread Pain Index (WPI)'],
    ['sss', 'Symptom Severity Scale (SSS)'],
    ['painScore', 'Pain Score (NRS 1–10)'],
    ['sleep', 'Sleep Quality (PSQI)'],
    ['fatigue', 'Fatigue Level'],
    ['exercise', 'Exercise Programme Engaged'],
    ['cbt', 'CBT / Pain Management Programme'],
    ['medications', 'Medications (Duloxetine / Pregabalin)'],
  ],

  'Pediatric Rheumatology': [
    ['childAge', 'Age of Child'],
    ['diagnosis', 'Diagnosis (JIA / JSLE / KD)'],
    ['jiaCategory', 'JIA Category (Oligoarticular / Polyarticular / Systemic)'],
    ['jointCount', 'Active Joint Count'],
    ['uveitisScreen', 'Slit Lamp Uveitis Screening'],
    ['cjadas', 'cJADAS Score'],
    ['dmard', 'DMARD / Biologic Therapy'],
    ['growth', 'Growth & Puberty Impact'],
  ],

  // ─── VETERINARY ───────────────────────────────────────────────────────────
  'Small Animal Medicine': [
    ['animalType', 'Animal Type (Dog / Cat)'],
    ['breed', 'Breed'],
    ['ageOfAnimal', 'Animal Age'],
    ['weight', 'Body Weight (kg)'],
    ['vaccinationStatus', 'Vaccination Status'],
    ['dewormingStatus', 'Deworming / Flea-Tick Status'],
    ['mainProblem', 'Chief Complaint'],
    ['feedingHabit', 'Diet / Feeding Habit'],
  ],

  'Large Animal Medicine': [
    ['species', 'Species (Cattle / Horse / Sheep / Goat)'],
    ['breed', 'Breed'],
    ['age', 'Age'],
    ['weight', 'Estimated Weight (kg)'],
    ['herdHistory', 'Herd / Flock History'],
    ['productionPurpose', 'Production Purpose (Dairy / Beef / Draft)'],
    ['vaccinationStatus', 'Vaccination / Deworming Status'],
    ['mainProblem', 'Chief Complaint'],
  ],

  'Veterinary Surgery': [
    ['animalType', 'Animal Type'],
    ['breed', 'Breed'],
    ['age', 'Age'],
    ['weight', 'Body Weight (kg)'],
    ['surgicalCondition', 'Surgical Condition'],
    ['preAnaesthesia', 'Pre-Anaesthetic Assessment (ASA)'],
    ['surgeryType', 'Surgery Type (Soft Tissue / Orthopaedic)'],
    ['anaesthesia', 'Anaesthesia Protocol'],
  ],

  'Veterinary Dentistry': [
    ['animalType', 'Animal Type'],
    ['breed', 'Breed'],
    ['age', 'Age'],
    ['dentalComplaint', 'Dental Complaint'],
    ['oralExam', 'Oral Examination Findings'],
    ['toothInvolved', 'Tooth / Teeth Involved'],
    ['periodontalGrade', 'Periodontal Grade'],
    ['dentalProcedure', 'Dental Procedure Planned'],
  ],

  'Exotic Animal Medicine': [
    ['species', 'Species (Bird / Reptile / Rabbit / Small Mammal)'],
    ['breed', 'Breed / Species Name'],
    ['age', 'Age'],
    ['weight', 'Weight (g or kg)'],
    ['dietHistory', 'Diet & Husbandry History'],
    ['environmentTemperature', 'Environmental Temperature / Lighting (Reptiles)'],
    ['mainProblem', 'Chief Complaint'],
    ['previousVetVisit', 'Previous Veterinary Treatment'],
  ],

  'Veterinary Oncology': [
    ['animalType', 'Animal Type'],
    ['breed', 'Breed'],
    ['age', 'Age'],
    ['tumorType', 'Tumor Type'],
    ['tumorLocation', 'Tumor Location'],
    ['stage', 'Stage / Grade'],
    ['histopathology', 'Histopathology Result'],
    ['treatmentPlanned', 'Treatment Plan (Surgery / Chemo / Radiation)'],
  ],

  'Veterinary Dermatology': [
    ['animalType', 'Animal Type'],
    ['breed', 'Breed'],
    ['age', 'Age'],
    ['skinLesionType', 'Skin Lesion Type'],
    ['distribution', 'Distribution / Body Area'],
    ['pruritus', 'Pruritus Level (0–10)'],
    ['allergyTest', 'Intradermal / IDST Allergy Test'],
    ['treatment', 'Current Treatment'],
  ],

  'Veterinary Ophthalmology': [
    ['animalType', 'Animal Type'],
    ['breed', 'Breed'],
    ['eyeAffected', 'Eye Affected'],
    ['redness', 'Redness'],
    ['watering', 'Watering / Discharge'],
    ['visionProblem', 'Vision Problem'],
    ['injuryHistory', 'Injury History'],
    ['previousTreatment', 'Previous Eye Treatment'],
  ],

  'Veterinary Reproduction': [
    ['animalType', 'Animal Type'],
    ['breed', 'Breed'],
    ['age', 'Age'],
    ['sex', 'Sex (Male / Female)'],
    ['reproductiveHistory', 'Reproductive History'],
    ['breedingGoal', 'Breeding Goal'],
    ['hormonalStatus', 'Hormonal Status (Oestrus / Pregnancy)'],
    ['procedure', 'Procedure (AI / ET / Whelping)'],
  ],

  'Aquatic Animal Medicine': [
    ['species', 'Aquatic Species'],
    ['tankEnvironment', 'Tank / Pond Environment'],
    ['waterQuality', 'Water Quality Parameters (pH / Temp / Ammonia)'],
    ['stockingDensity', 'Stocking Density'],
    ['mainProblem', 'Chief Complaint / Disease Signs'],
    ['mortality', 'Mortality Rate (%)'],
    ['previousTreatment', 'Previous Treatment'],
  ],

  // ─── GENERAL (fallback) ───────────────────────────────────────────────────
  General: [
    ['bloodPressure', 'Blood Pressure'],
    ['temperature', 'Temperature'],
    ['pulse', 'Pulse'],
    ['weight', 'Weight'],
    ['spo2', 'SpO₂'],
  ],
};